import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const font = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${font.className} w-screen h-screen overflow-auto`}>
        {children}
      </body>
    </html>
  );
}
